fixes

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -33,7 +33,12 @@ workflows:
         script: flutter --version
       - name: Install dependencies
         script: |
-          flutter pub get
+          if [ -f "pubspec.yaml" ]; then
+            flutter pub get
+          else
+            echo "pubspec.yaml not found in the current directory."
+            exit 1
+          fi
       - name: Run code generation
         script: |
           flutter pub run build_runner build --delete-conflicting-outputs
